project_id = "kraak-group"

[auth]
enabled = true
site_url = "http://localhost:4200"
additional_redirect_urls = [
  "http://localhost:4200/auth/callback",
  "http://localhost:4200/auth/reset",
  "http://localhost:4200/connexion",
  "http://localhost:4200/mot-de-passe-oublie",
  "http://localhost:4300/auth/callback",
  "http://localhost:4300/auth/reset",
  "http://localhost:4300/connexion",
  "http://localhost:4300/mot-de-passe-oublie",
  "https://client-six-indol-58.vercel.app/auth/callback",
  "https://client-six-indol-58.vercel.app/auth/reset",
  "https://client-six-indol-58.vercel.app/connexion",
  "https://client-six-indol-58.vercel.app/mot-de-passe-oublie",
  "https://kraak-consulting.vercel.app/auth/callback",
  "https://kraak-consulting.vercel.app/auth/reset",
  "https://kraak-consulting.vercel.app/connexion",
  "https://kraak-consulting.vercel.app/mot-de-passe-oublie",
  "https://kraak-consulting-git-staging-ange230700s-projects.vercel.app/auth/callback",
  "https://kraak-consulting-git-staging-ange230700s-projects.vercel.app/auth/reset",
  "https://kraak-consulting-git-staging-ange230700s-projects.vercel.app/connexion",
  "https://kraak-consulting-git-staging-ange230700s-projects.vercel.app/mot-de-passe-oublie",
  "https://kraak-consulting-*-ange230700s-projects.vercel.app/auth/callback",
  "https://kraak-consulting-*-ange230700s-projects.vercel.app/auth/reset",
  "https://kraak-consulting-*-ange230700s-projects.vercel.app/connexion",
  "https://kraak-consulting-*-ange230700s-projects.vercel.app/mot-de-passe-oublie",
  "kraak://auth/callback",
  "kraak://auth/reset",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "1m"

[auth.email.template.confirmation]
subject = "Confirmez votre inscription KRAAK"
content_path = "./supabase/templates/auth/confirmation.html"

[auth.email.template.recovery]
subject = "Réinitialisez votre mot de passe KRAAK"
content_path = "./supabase/templates/auth/recovery.html"
