import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { buildDocsIndexes } from './generate-docs-index.mjs';

const repoRoot = process.cwd();
const scriptPath = path.join(repoRoot, 'scripts', 'generate-docs-index.mjs');

function writeMarkdown(root, file, content) {
  const target = path.join(root, file);

  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(
    target,
    content.trimStart().replace(/\n/g, '\n') + '\n',
    'utf8',
  );
}

function createFixtureRepository() {
  const root = mkdtempSync(path.join(os.tmpdir(), 'kraak-docs-index-'));

  writeMarkdown(
    root,
    'README.md',
    `
# Fixture repository
`,
  );
  writeMarkdown(
    root,
    'AGENTS.md',
    `
# Agents
`,
  );
  writeMarkdown(
    root,
    'ARCHITECTURE.md',
    `
# Architecture
`,
  );
  writeMarkdown(
    root,
    'docs/architecture/OVERVIEW.md',
    `
---
status: active
owner: platform
last_reviewed: 2026-07-23
source_of_truth: true
---

# Vue d'ensemble
`,
  );
  writeMarkdown(
    root,
    'docs/operations/DEPLOYMENT.md',
    `
---
status: active
owner: platform
last_reviewed: 2026-07-23
source_of_truth: true
---

# Deploiement
`,
  );
  writeMarkdown(
    root,
    'docs/reference/STYLE_GUIDE.md',
    `
---
status: reference
owner: platform
last_reviewed: 2026-07-23
source_of_truth: false
---

# Style guide
`,
  );
  writeMarkdown(
    root,
    'docs/generated/README.md',
    `
---
status: active
owner: platform
last_reviewed: 2026-07-23
source_of_truth: true
---

# Artefacts generes
`,
  );
  writeMarkdown(
    root,
    'docs/decisions/ARC-02-second-decision.md',
    `
---
status: active
owner: platform
last_reviewed: 2026-07-23
source_of_truth: true
---

# ARC-02 - Seconde decision

- **Statut** : Acceptee
- **Date** : 2026-02-02
`,
  );
  writeMarkdown(
    root,
    'docs/decisions/ARC-01-first-decision.md',
    `
---
status: active
owner: platform
last_reviewed: 2026-07-23
source_of_truth: true
---

# ARC-01 - Premiere decision

| Champ | Valeur |
| --- | --- |
| **Statut** | Acceptee |
| **Date** | 2026-01-01 |
`,
  );
  writeMarkdown(
    root,
    'docs/archive/pilot/README.md',
    `
---
status: historical
owner: platform
archived_on: 2026-03-01
---

# Archive pilote

## Pourquoi ces documents sont archives

Ce dossier conserve le pilote historique.
`,
  );

  return root;
}

function runScript(root, args) {
  return spawnSync(process.execPath, [scriptPath, ...args], {
    cwd: root,
    encoding: 'utf8',
    timeout: 30_000,
  });
}

test('Given documentation files, When indexes are built, Then generated content is deterministic and ordered', async () => {
  const root = createFixtureRepository();

  try {
    const indexes = await buildDocsIndexes(root, { today: '2026-07-24' });
    const docsIndex = indexes.get('docs/README.md');
    const adrIndex = indexes.get('docs/decisions/README.md');
    const archiveIndex = indexes.get('docs/archive/README.md');

    assert.match(docsIndex, /last_reviewed: 2026-07-24/);
    assert.match(docsIndex, /## Catalogue des documents actifs/);
    assert.match(
      docsIndex,
      /\| `architecture\/OVERVIEW\.md`\s+\| active \| true\s+\| Vue d'ensemble\s+\|/,
    );
    assert.doesNotMatch(docsIndex, /reference\/STYLE_GUIDE/);
    assert.match(
      docsIndex,
      /<!-- Generated by scripts\/generate-docs-index\.mjs/,
    );

    assert.match(
      adrIndex,
      /\| `ARC-01` \| \[Premiere decision\]\(ARC-01-first-decision\.md\)\s+\| Acceptee \| 2026-01-01 \|[\s\S]*\| `ARC-02` \| \[Seconde decision\]\(ARC-02-second-decision\.md\) \| Acceptee \| 2026-02-02 \|/,
    );

    assert.match(
      archiveIndex,
      /\| `pilot\/`\s+\| historical \| 2026-03-01\s+\| Archive pilote \| Ce dossier conserve le pilote historique\. \|/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('Given stale generated indexes, When check mode runs, Then it fails without writing files', () => {
  const root = createFixtureRepository();

  try {
    writeMarkdown(root, 'docs/README.md', '# Old docs index');

    const result = runScript(root, ['--check']);
    const docsIndex = readFileSync(path.join(root, 'docs/README.md'), 'utf8');

    assert.equal(result.status, 1);
    assert.match(result.stderr, /docs\/README\.md is not up to date/);
    assert.match(result.stderr, /docs:index:write/);
    assert.match(docsIndex, /^# Old docs index/m);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('Given documentation indexes, When write runs before check, Then the check passes', () => {
  const root = createFixtureRepository();

  try {
    const writeResult = runScript(root, ['--write']);

    assert.equal(
      writeResult.status,
      0,
      writeResult.stderr || writeResult.stdout,
    );

    const checkResult = runScript(root, ['--check']);

    assert.equal(
      checkResult.status,
      0,
      checkResult.stderr || checkResult.stdout,
    );
    assert.match(
      readFileSync(path.join(root, 'docs/decisions/README.md'), 'utf8'),
      /# Architecture Decision Records \(ADR\)/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
